import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat, Playfair_Display } from "next/font/google";
import "./globals.css";
import QueryProvider from '@/providers/QueryProvider';
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const montserrat = Montserrat({
  weight: ['700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const whatsappLink = "https://wa.me/919825734038";

  return (
    <html lang="en" className="overflow-y-scroll">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${montserrat.variable} ${playfair.variable} antialiased`}
      >
        <QueryProvider>
          {children}

          {/* ✅ Floating WhatsApp Button */}
          <a
            href={whatsappLink}
            target="_blank"
            rel="noopener noreferrer"
            className="fixed bottom-6 right-6 z-50 bg-green-500 rounded-full shadow-lg p-2 hover:scale-110 transition-transform"
          >
            <Image
              src="/Images/whatsapp.png"
              alt="WhatsApp"
              width={48}
              height={48}
            />
          </a>
        </QueryProvider>
      </body>
    </html>
  );
}
